Feat/add humanizeBytes and showDeltaFileSizes functions
MrPowers/jodie pull request #82
Opened 2023-11-17 16:34 UTC by sebastian2296

2023-11-17 19:59 UTC, brayanjuls requested changes
Good effort! I added some comments and I will finish the review for the unit test later today.

2023-11-17 19:59 UTC, brayanjuls commented on src/main/scala/mrpowers/jodie/DeltaHelpers.scala
> +    val avgFileSizeInBytes = if (numberOfFiles == 0) 0 else Math.round(sizeInBytes / numberOfFiles)
This code section seems equal to what deltaFileSizes function, could you try to reuse that other function in here?

2023-11-17 19:59 UTC, brayanjuls commented on src/main/scala/mrpowers/jodie/DeltaHelpers.scala
> +    val formatter = java.text.NumberFormat.getIntegerInstance
I think we can remove this line of code as is not being used.

2023-11-17 19:59 UTC, brayanjuls commented on src/main/scala/mrpowers/jodie/DeltaHelpers.scala
> +    val humanized_average_file_size = humanizeBytes(avgFileSizeInBytes)
let's stick with lowerCamelCase for variable naming as it is the convention in scala.

2023-12-05 20:33 UTC, sebastian2296 commented on src/main/scala/mrpowers/jodie/DeltaHelpers.scala
> +    val avgFileSizeInBytes = if (numberOfFiles == 0) 0 else Math.round(sizeInBytes / numberOfFiles)
Just implemented the change to reuse deltaFileSizes function. In order to make it work properly I added a type annotation to the signature (it was inferred as Map[String, AnyVal], which was incompatible with HumanizeBytes input type).

2024-01-05 12:20 UTC, brayanjuls commented
LGTM

2024-01-05 12:21 UTC, merged